# Generated by Django 5.2.10 on 2026-01-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'can view book'), ('can_create', 'Can add books'), ('can_edit', 'can edit book'), ('can_delete', 'can delete book'))},
        ),
    ]
