# Generated by Django 5.2.10 on 2026-01-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'can view book'), ('can_create', 'can add book'), ('can_edit', 'can edit book'), ('can_delete', 'can delete book'))},
        ),
    ]
