# Generated by Django 5.2.10 on 2026-01-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_author_id_alter_book_id_alter_librarian_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add books'), ('can_change_book', 'can edit book'), ('can_delete_book', 'can delete book'))},
        ),
    ]
